[package]
name = "thus-spoke-zakura"
autobins = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "ths"
path = "src/main.rs"

[features]
release-distribution = []

[dependencies]
anyhow.workspace = true
clap.workspace = true
ctrlc.workspace = true
directories.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3"
