use std::{
    sync::atomic::{AtomicU64, Ordering},
    time::Duration,
};

use anyhow::{Context, Result, bail};
use reqwest::Client;
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use serde_json::{Value, json};
use zcash_keys::address::Address;
use zcash_primitives::transaction::Transaction;
use zcash_protocol::consensus::{BlockHeight, BranchId};

use crate::wallet::regtest_network;

const CALL_TIMEOUT: Duration = Duration::from_secs(30);
const GENERATE_TIMEOUT: Duration = Duration::from_secs(3600);

fn call_timeout(method: &str) -> Duration {
    if method == "generate" {
        GENERATE_TIMEOUT
    } else {
        CALL_TIMEOUT
    }
}

#[derive(Clone)]
pub struct NodeRpc {
    endpoint: String,
    client: Client,
    request_id: std::sync::Arc<AtomicU64>,
    chain_anchor: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChainInfo {
    pub chain: String,
    pub blocks: u64,
    #[serde(default)]
    pub bestblockhash: String,
    #[serde(default)]
    pub verificationprogress: f64,
}

#[derive(Debug, Deserialize)]
struct Envelope<T> {
    result: Option<T>,
    error: Option<Value>,
}

impl NodeRpc {
    pub fn new(endpoint: String) -> Self {
        Self {
            endpoint,
            // All supported node modes use a local endpoint (including Docker's
            // internal hostnames). Never route RPC through a proxy or redirect.
            client: Client::builder()
                .no_proxy()
                .redirect(reqwest::redirect::Policy::none())
                .build()
                .expect("initializing local Zakura RPC client"),
            request_id: Default::default(),
            chain_anchor: None,
        }
    }

    pub fn with_chain_anchor(mut self, hash: String) -> Self {
        self.chain_anchor = Some(hash);
        self
    }

    pub fn is_external(&self) -> bool {
        self.chain_anchor.is_some()
    }

    pub async fn validate_chain_anchor(&self) -> Result<()> {
        if let Some(expected) = &self.chain_anchor {
            let actual: String = self.call("getblockhash", json!([1])).await.context(
                "external chain anchor is unavailable; restore the node or reset the ths wallet and prepare again",
            )?;
            anyhow::ensure!(
                &actual == expected,
                "external chain changed at the wallet's birthday; reset the ths wallet and prepare again"
            );
        }
        Ok(())
    }

    pub async fn call<T: DeserializeOwned>(&self, method: &str, params: Value) -> Result<T> {
        self.call_within(call_timeout(method), method, params).await
    }

    async fn call_within<T: DeserializeOwned>(
        &self,
        timeout: Duration,
        method: &str,
        params: Value,
    ) -> Result<T> {
        let id = self.request_id.fetch_add(1, Ordering::Relaxed);
        let response = self
            .client
            .post(&self.endpoint)
            .timeout(timeout)
            .json(&json!({"jsonrpc":"2.0","id":id,"method":method,"params":params}))
            .send()
            .await
            .map_err(|error| {
                let context = if error.is_timeout() {
                    format!("Zakura {method} timed out after {timeout:?}")
                } else {
                    format!("calling Zakura {method}")
                };
                anyhow::Error::new(error).context(context)
            })?;
        let status = response.status();
        anyhow::ensure!(
            !status.is_redirection(),
            "local Zakura RPC must not redirect to another endpoint"
        );
        if status == reqwest::StatusCode::UNAUTHORIZED {
            bail!(
                "Zakura RPC requires authentication; use the dedicated Regtest configuration generated by ths prepare"
            );
        }
        let envelope: Envelope<T> = response.json().await.context("decoding Zakura response")?;
        if let Some(error) = envelope.error {
            bail!("Zakura {method} failed: {error}");
        }
        if !status.is_success() {
            bail!("Zakura {method} returned HTTP {status}");
        }
        envelope
            .result
            .context("Zakura response did not contain a result")
    }

    pub async fn chain_info(&self) -> Result<ChainInfo> {
        self.call("getblockchaininfo", json!([])).await
    }
    pub async fn generate(&self, blocks: u32) -> Result<Vec<String>> {
        self.validate_network().await?;
        self.validate_chain_anchor().await?;
        self.call("generate", json!([blocks])).await
    }

    pub async fn validate_network(&self) -> Result<ChainInfo> {
        let info: Value = self.call("getblockchaininfo", json!([])).await?;
        validate_network_info(&info)?;
        // Zakura reports BIP70 "test" for both Testnet and Regtest. Verify the
        // genesis block as well as the upgrade schedule before any mutation.
        let genesis: String = self.call("getblockhash", json!([0])).await?;
        anyhow::ensure!(
            genesis == "029f11d80ef9765602235e1bc9727e3eb6ba20839319f761fee920d63401e327",
            "ths requires the standard Regtest genesis block"
        );
        Ok(serde_json::from_value(info)?)
    }

    pub async fn validate_treasury(&self, address: &str) -> Result<()> {
        let template: Value = self.call("getblocktemplate", json!([])).await?;
        validate_treasury_template(&template, address)
    }
    pub async fn block(&self, id: &str) -> Result<Value> {
        self.call("getblock", json!([id, 2])).await
    }
    pub async fn transaction(&self, txid: &str) -> Result<Value> {
        self.call("getrawtransaction", json!([txid, 1])).await
    }
    pub async fn mempool(&self) -> Result<Vec<String>> {
        self.call("getrawmempool", json!([])).await
    }
}

fn validate_network_info(info: &Value) -> Result<()> {
    anyhow::ensure!(
        info["chain"]
            .as_str()
            .is_some_and(|s| s.eq_ignore_ascii_case("regtest") || s == "test"),
        "ths requires Regtest; node reports {}",
        info["chain"]
    );
    let upgrades = info["upgrades"]
        .as_object()
        .context("node omitted network upgrade information")?;
    let expected = [
        "Overwinter",
        "Sapling",
        "Blossom",
        "Heartwood",
        "Canopy",
        "NU5",
        "NU6",
    ];
    for name in expected {
        anyhow::ensure!(
            upgrades.values().any(|upgrade| upgrade["name"] == name
                && upgrade["activationheight"].as_u64() == Some(1)),
            "incompatible Regtest configuration: {name} must activate at block 1; use the configuration generated by ths"
        );
    }
    for upgrade in upgrades.values() {
        anyhow::ensure!(
            upgrade["name"]
                .as_str()
                .is_some_and(|name| expected.contains(&name)),
            "unsupported Regtest upgrade {}; use the configuration generated by ths",
            upgrade["name"]
        );
    }
    Ok(())
}

fn validate_treasury_template(template: &Value, address: &str) -> Result<()> {
    let params = regtest_network();
    let Some(Address::Transparent(expected)) = Address::decode(&params, address) else {
        bail!("invalid treasury address");
    };
    let height = u32::try_from(
        template["height"]
            .as_u64()
            .context("block template omitted height")?,
    )?;
    let raw = hex::decode(
        template
            .pointer("/coinbasetxn/data")
            .and_then(Value::as_str)
            .context("block template omitted coinbase transaction")?,
    )?;
    let tx = Transaction::read(
        &raw[..],
        BranchId::for_height(&params, BlockHeight::from_u32(height)),
    )?;
    anyhow::ensure!(
        tx.transparent_bundle().is_some_and(|bundle| bundle
            .vout
            .iter()
            .any(|output| output.recipient_address() == Some(expected)
                && u64::from(output.value()) > 0)),
        "Zakura mining payout does not match this wallet's treasury ({address}); restart your node with the configuration generated by ths prepare"
    );
    Ok(())
}

#[cfg(test)]
pub(crate) mod testing {
    use super::*;
    use axum::{Json, Router, routing::post};
    use std::sync::{Arc, Mutex};

    pub struct MockRpc {
        pub rpc: NodeRpc,
        pub calls: Arc<Mutex<Vec<Value>>>,
        task: tokio::task::JoinHandle<()>,
    }

    impl Drop for MockRpc {
        fn drop(&mut self) {
            self.task.abort();
        }
    }

    impl MockRpc {
        pub async fn start(
            handler: impl Fn(&Value) -> Result<Value, Value> + Send + Sync + 'static,
        ) -> Self {
            let calls = Arc::new(Mutex::new(vec![]));
            let requests = calls.clone();
            let handler = Arc::new(handler);
            let app = Router::new().route(
                "/",
                post(move |Json(request): Json<Value>| {
                    let handler = handler.clone();
                    let requests = requests.clone();
                    async move {
                        requests.lock().unwrap().push(request.clone());
                        Json(match handler(&request) {
                            Ok(result) => {
                                json!({"jsonrpc":"2.0","id":request["id"],"result":result})
                            }
                            Err(error) => json!({"jsonrpc":"2.0","id":request["id"],"error":error}),
                        })
                    }
                }),
            );
            let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
            let rpc = NodeRpc::new(format!("http://{}", listener.local_addr().unwrap()));
            let task = tokio::spawn(async move {
                axum::serve(listener, app).await.unwrap();
            });
            Self { rpc, calls, task }
        }

        pub fn count(&self, method: &str) -> usize {
            self.calls
                .lock()
                .unwrap()
                .iter()
                .filter(|request| request["method"] == method)
                .count()
        }
    }

    pub fn regtest_reply(request: &Value) -> Result<Value, Value> {
        match request["method"].as_str().unwrap() {
            "getblockchaininfo" => {
                let upgrades: serde_json::Map<String, Value> = [
                    "Overwinter",
                    "Sapling",
                    "Blossom",
                    "Heartwood",
                    "Canopy",
                    "NU5",
                    "NU6",
                ]
                .into_iter()
                .map(|name| (name.into(), json!({"name":name,"activationheight":1})))
                .collect();
                Ok(json!({"chain":"test","blocks":10,"bestblockhash":"tip","upgrades":upgrades}))
            }
            "getblockhash" if request["params"][0] == 0 => Ok(json!(
                "029f11d80ef9765602235e1bc9727e3eb6ba20839319f761fee920d63401e327"
            )),
            "getblockhash" => Ok(json!("original-anchor")),
            "generate" => Ok(json!(["mined-block"])),
            _ => Err(json!({"code":-1,"message":"unexpected test RPC"})),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::testing::{MockRpc, regtest_reply};
    use super::*;

    #[test]
    fn only_mining_gets_the_one_hour_timeout() {
        assert_eq!(call_timeout("generate"), Duration::from_secs(3600));
        for method in ["getblockchaininfo", "getblockhash", "sendrawtransaction"] {
            assert_eq!(call_timeout(method), Duration::from_secs(30));
        }
    }

    #[tokio::test]
    async fn call_gives_up_on_a_node_that_never_answers() {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let rpc = NodeRpc::new(format!("http://{}", listener.local_addr().unwrap()));
        // The outer deadline makes a missing request timeout fail, not hang.
        let error = tokio::time::timeout(
            Duration::from_secs(2),
            rpc.call_within::<Value>(Duration::from_millis(50), "getblockcount", json!([])),
        )
        .await
        .expect("RPC request did not honor its timeout")
        .unwrap_err();
        assert_eq!(
            error.to_string(),
            "Zakura getblockcount timed out after 50ms"
        );
        assert!(error.downcast_ref::<reqwest::Error>().unwrap().is_timeout());
    }

    #[tokio::test]
    async fn rpc_timeout_also_covers_reading_the_response_body() {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};

        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let rpc = NodeRpc::new(format!("http://{}", listener.local_addr().unwrap()));
        let server = tokio::spawn(async move {
            let (mut socket, _) = listener.accept().await.unwrap();
            let mut request_start = [0; 1];
            socket.read_exact(&mut request_start).await.unwrap();
            socket
                .write_all(b"HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 100\r\n\r\n{")
                .await
                .unwrap();
            std::future::pending::<()>().await;
        });
        let result = tokio::time::timeout(
            Duration::from_secs(2),
            rpc.call_within::<Value>(Duration::from_millis(100), "getblockcount", json!([])),
        )
        .await;
        server.abort();
        let error = result
            .expect("RPC response body did not honor its timeout")
            .unwrap_err();
        assert_eq!(error.to_string(), "decoding Zakura response");
        assert!(error.downcast_ref::<reqwest::Error>().unwrap().is_timeout());
    }

    #[tokio::test]
    async fn rpc_does_not_follow_http_redirects() {
        use axum::{Router, response::Redirect, routing::post};
        let destination = MockRpc::start(regtest_reply).await;
        let location = destination.rpc.endpoint.clone();
        let app = Router::new().route(
            "/",
            post(move || {
                let redirect = Redirect::temporary(&location);
                async move { redirect }
            }),
        );
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let rpc = NodeRpc::new(format!("http://{}", listener.local_addr().unwrap()));
        let server = tokio::spawn(async move { axum::serve(listener, app).await.unwrap() });
        let error = rpc.chain_info().await.unwrap_err();
        server.abort();
        assert!(error.to_string().contains("must not redirect"));
        assert_eq!(destination.count("getblockchaininfo"), 0);
    }

    #[tokio::test]
    async fn mining_rechecks_the_external_anchor_on_every_request() {
        use std::sync::{Arc, atomic::AtomicBool};
        let replaced = Arc::new(AtomicBool::new(false));
        let node = replaced.clone();
        let server = MockRpc::start(move |request| {
            if request["method"] == "getblockhash"
                && request["params"][0] == 1
                && node.load(Ordering::SeqCst)
            {
                Ok(json!("replacement-anchor"))
            } else {
                regtest_reply(request)
            }
        })
        .await;
        let rpc = server
            .rpc
            .clone()
            .with_chain_anchor("original-anchor".into());
        rpc.generate(1).await.unwrap();
        replaced.store(true, Ordering::SeqCst);
        let error = rpc.generate(1).await.unwrap_err();
        assert!(error.to_string().contains("external chain changed"));
        assert_eq!(server.count("generate"), 1);
    }

    #[tokio::test]
    async fn missing_external_anchor_prevents_mining() {
        let server = MockRpc::start(|request| {
            if request["method"] == "getblockhash" && request["params"][0] == 1 {
                Err(json!({"code":-8,"message":"block does not exist"}))
            } else {
                regtest_reply(request)
            }
        })
        .await;
        let rpc = server
            .rpc
            .clone()
            .with_chain_anchor("original-anchor".into());
        assert!(
            rpc.generate(1)
                .await
                .unwrap_err()
                .to_string()
                .contains("anchor is unavailable")
        );
        assert_eq!(server.count("generate"), 0);
    }

    fn compatible_info() -> Value {
        let upgrades: serde_json::Map<String, Value> = [
            "Overwinter",
            "Sapling",
            "Blossom",
            "Heartwood",
            "Canopy",
            "NU5",
            "NU6",
        ]
        .into_iter()
        .map(|name| (name.into(), json!({"name":name,"activationheight":1})))
        .collect();
        json!({"chain":"regtest","upgrades":upgrades})
    }

    #[test]
    fn accepts_only_the_wallets_regtest_schedule() {
        let mut info = compatible_info();
        validate_network_info(&info).unwrap();
        info["chain"] = json!("test");
        validate_network_info(&info).unwrap();
        info["chain"] = json!("main");
        assert!(validate_network_info(&info).is_err());
        info = compatible_info();
        info["upgrades"]["NU6"]["activationheight"] = json!(2);
        assert!(validate_network_info(&info).is_err());
        info = compatible_info();
        info["upgrades"]["NU6.1"] = json!({"name":"NU6.1","activationheight":10});
        assert!(validate_network_info(&info).is_err());
    }

    #[test]
    fn requires_a_positive_coinbase_payment_to_the_prepared_treasury() {
        // Coinbase from a local Zakura getblocktemplate response (NU6, block 106).
        let raw = concat!(
            "050000800a27a7265510e7c8000000006a00000001",
            "0000000000000000000000000000000000000000000000000000000000000000",
            "ffffffff1a016a17f09f8cb83a20746875732d73706f6b652d7a616b757261ffffffff01",
            "40be4025000000001976a914ac84b19c72e770c4042c307da010fe70754e84da88ac000000"
        );
        let treasury = "tmRSYWtjmzRstCeX9c7hm8GsBRs4ndQshUf";
        let mut template = json!({"height":106,"coinbasetxn":{"data":raw}});
        validate_treasury_template(&template, treasury).unwrap();
        let error = validate_treasury_template(&template, "tmPSTyaDo5AngKdRPup6tSsjwzBFMFXbXJp")
            .unwrap_err();
        assert!(error.to_string().contains("mining payout does not match"));
        template["coinbasetxn"]["data"] =
            json!(raw.replace("40be402500000000", "0000000000000000"));
        assert!(validate_treasury_template(&template, treasury).is_err());
        template["coinbasetxn"]["data"] = json!("not hex");
        assert!(validate_treasury_template(&template, treasury).is_err());
        assert!(validate_treasury_template(&json!({"height":106}), treasury).is_err());
    }
}
